---

samples : samples.tsv

workdir: scratch/
resultdir: results/

fqdir: data/

fastp:
  qualified_quality_phred: 15 # the quality value that a base is qualified. Default 15 means phred quality >=Q15 is qualified. (int [=15])

# kallisto fasta file that will be indexed by Kallisto
kallisto:
  fasta_ref: refs/petunia.transcripts.fasta
  fragment-length: 90
  sd: 30
  bootstrap: 100

sleuth:
  p_value: 0.05
  info: /home/mgalland/01_sequencing_runs/20160216_mRNAs_20_accessions/seqdesign.modified.txt
