---

workdir: scratch/
resultdir: results/

fqdir: trimmed/

# kallisto fasta file that will be indexed by Kallisto
kallisto:
  fasta_ref: /general/transcriptome.fasta
  fragment-length: 90
  sd: 30
  bootstrap: 100

sleuth:
  info: /home/mgalland/01_sequencing_runs/20160216_mRNAs_20_accessions/seqdesign.modified.txt
