name: rnaseq
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
    - python=3.7.2
    - samtools=1.3.1
    - snakemake=5.3.0
    - pyyaml=5.1
    - kallisto=0.45.0
    - r-sleuth=0.30.0
    - fastp=0.19.7
