name: rnaseq
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
    - samtools=1.9.0
    - snakemake=5.3.0
    - pyyaml=5.1
    - kallisto=0.45.0
    - r-sleuth=0.30.0
    - fastp=0.19.7
    - r-tidyverse=1.2.1
    - r-optparse=1.6.1
