name: kallisto
channels:
  - bioconda
  - r
  - conda-forge
dependencies:
  - bioconda::snakemake=5.26.0  
  - bioconda::fastp = 0.19.5
  - bioconda::kallisto=0.45.0
  - r::r-sleuth=0.30.0=r36_2
  - r::r-optparse=1.6.6=r36h6115d3f_1
  - r::r-dplyr=1.0.2=r36h710217c_0 
